input:
  label: "mqtt_input1"
  mqtt:
    urls: ["tcp://emqxedge:1883"]
    client_id: "mqtt_client_in1"
    connect_timeout: 30s
    topics: ["test/input1"]
    auto_replay_nacks: true

pipeline:
  processors:
    - mapping: |
        let id = uuid_v4()
        root.sensorid = this.id
        root.value = this.val
        root.result = this.val > 10
        root.annotations.id = $id

output:
  label: "mqtt_output1"
  mqtt:
    urls: ["tcp://emqxedge:1883"]
    client_id: "mqtt_client_out1"
    connect_timeout: 30s
    topic: "test/output/1"
    qos: 1
    retained: false
